services:
  php:
    build: ./docker/php
    container_name: app-symfony-php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    command: bash -c "if [ ! -f .env.local ] && [ -f .env.example ]; then cp .env.example .env.local; fi && if [ ! -d vendor ]; then composer install --no-progress --prefer-dist; fi && php-fpm"

  nginx:
    image: nginx:1.25-alpine
    container_name: app-symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: app-symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-symfony-db
      MYSQL_USER: appDBuser
      MYSQL_PASSWORD: appDBpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   # volume nommé pour persister les données

  adminer:
    image: adminer
    container_name: app-symfony-adminer
    restart: always
    ports:
      - "8081:8080"  # accès sur http://localhost:8081

  mailhog:
    image: mailhog/mailhog
    container_name: app-symfony-mailhog
    restart: always
    ports:
      - "8025:8025"  # interface web: http://localhost:8025
      - "1025:1025"  # port SMTP

volumes:
  db_data:   # déclaration du volume
